CLASS zsubmarine DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES
      if_oo_adt_classrun.
    DATA horizontal TYPE i.
    DATA depth TYPE i.
    DATA aim TYPE i.
    METHODS dive
      IMPORTING
        course TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
    CONSTANTS direction_forward TYPE string VALUE 'forward' ##NO_TEXT.
    CONSTANTS direction_down TYPE string VALUE 'down' ##NO_TEXT.
    CONSTANTS direction_up TYPE string VALUE 'up' ##NO_TEXT.
    METHODS get_riddle_input
      RETURNING VALUE(riddle) TYPE string.
ENDCLASS.

CLASS zsubmarine IMPLEMENTATION.

  METHOD dive.
    SPLIT course AT cl_abap_char_utilities=>newline INTO TABLE DATA(course_tab).
    LOOP AT course_tab ASSIGNING FIELD-SYMBOL(<course>).
      SPLIT <course> AT space INTO DATA(direction) DATA(units).
      CASE direction.
        WHEN direction_forward.
          horizontal = horizontal + units.
          depth = depth + aim * units.
        WHEN direction_down.
          aim = aim  + units.
        WHEN direction_up.
          aim = aim - units.
      ENDCASE.
    ENDLOOP.
  ENDMETHOD.

  METHOD if_oo_adt_classrun~main.
    dive( get_riddle_input( ) ).
    out->write( horizontal * depth ).
  ENDMETHOD.

  METHOD get_riddle_input.
    riddle =
|forward 1\n| &&
|down 5\n| &&
|down 6\n| &&
|down 2\n| &&
|forward 8\n| &&
|up 3\n| &&
|up 2\n| &&
|down 2\n| &&
|forward 9\n| &&
|forward 7\n| &&
|down 2\n| &&
|forward 5\n| &&
|down 2\n| &&
|forward 2\n| &&
|forward 1\n| &&
|down 8\n| &&
|forward 5\n| &&
|down 6\n| &&
|up 9\n| &&
|down 7\n| &&
|forward 6\n| &&
|forward 7\n| &&
|forward 8\n| &&
|up 3\n| &&
|down 8\n| &&
|forward 9\n| &&
|forward 5\n| &&
|forward 2\n| &&
|down 3\n| &&
|down 3\n| &&
|down 6\n| &&
|down 6\n| &&
|down 8\n| &&
|down 4\n| &&
|forward 1\n| &&
|up 9\n| &&
|down 7\n| &&
|up 6\n| &&
|down 2\n| &&
|down 8\n| &&
|forward 1\n| &&
|forward 7\n| &&
|forward 4\n| &&
|forward 1\n| &&
|forward 7\n| &&
|down 1\n| &&
|down 9\n| &&
|forward 6\n| &&
|forward 6\n| &&
|forward 7\n| &&
|forward 3\n| &&
|up 7\n| &&
|forward 7\n| &&
|up 1\n| &&
|forward 3\n| &&
|forward 4\n| &&
|up 4\n| &&
|forward 6\n| &&
|down 8\n| &&
|down 7\n| &&
|forward 4\n| &&
|up 6\n| &&
|up 8\n| &&
|down 5\n| &&
|down 6\n| &&
|forward 2\n| &&
|forward 7\n| &&
|forward 5\n| &&
|forward 4\n| &&
|down 5\n| &&
|down 8\n| &&
|down 4\n| &&
|down 4\n| &&
|down 3\n| &&
|forward 3\n| &&
|down 8\n| &&
|forward 7\n| &&
|up 6\n| &&
|down 3\n| &&
|down 7\n| &&
|down 3\n| &&
|forward 2\n| &&
|up 8\n| &&
|down 7\n| &&
|down 6\n| &&
|down 3\n| &&
|up 5\n| &&
|up 4\n| &&
|down 2\n| &&
|down 5\n| &&
|up 9\n| &&
|down 8\n| &&
|up 7\n| &&
|up 8\n| &&
|forward 7\n| &&
|down 9\n| &&
|up 5\n| &&
|down 5\n| &&
|down 5\n| &&
|up 4\n| &&
|down 4\n| &&
|up 3\n| &&
|down 1\n| &&
|down 4\n| &&
|down 7\n| &&
|forward 2\n| &&
|forward 9\n| &&
|up 8\n| &&
|down 8\n| &&
|forward 6\n| &&
|forward 8\n| &&
|down 6\n| &&
|down 2\n| &&
|forward 2\n| &&
|forward 7\n| &&
|up 7\n| &&
|down 4\n| &&
|forward 1\n| &&
|down 4\n| &&
|forward 2\n| &&
|up 3\n| &&
|forward 8\n| &&
|forward 7\n| &&
|forward 8\n| &&
|down 2\n| &&
|down 9\n| &&
|down 5\n| &&
|forward 7\n| &&
|down 7\n| &&
|forward 8\n| &&
|forward 2\n| &&
|up 2\n| &&
|forward 9\n| &&
|down 3\n| &&
|up 7\n| &&
|forward 2\n| &&
|down 4\n| &&
|up 3\n| &&
|up 8\n| &&
|forward 4\n| &&
|forward 4\n| &&
|forward 3\n| &&
|up 3\n| &&
|forward 5\n| &&
|forward 5\n| &&
|down 9\n| &&
|down 4\n| &&
|up 2\n| &&
|down 8\n| &&
|down 5\n| &&
|down 8\n| &&
|up 7\n| &&
|down 3\n| &&
|down 7\n| &&
|up 9\n| &&
|down 7\n| &&
|up 5\n| &&
|down 5\n| &&
|forward 2\n| &&
|forward 2\n| &&
|forward 6\n| &&
|down 4\n| &&
|up 3\n| &&
|forward 1\n| &&
|forward 3\n| &&
|forward 4\n| &&
|down 2\n| &&
|forward 2\n| &&
|down 1\n| &&
|down 2\n| &&
|down 3\n| &&
|forward 8\n| &&
|forward 1\n| &&
|down 5\n| &&
|forward 3\n| &&
|up 2\n| &&
|down 2\n| &&
|forward 3\n| &&
|forward 1\n| &&
|up 4\n| &&
|up 1\n| &&
|up 2\n| &&
|forward 4\n| &&
|forward 8\n| &&
|down 7\n| &&
|forward 2\n| &&
|down 8\n| &&
|forward 6\n| &&
|forward 3\n| &&
|up 7\n| &&
|down 3\n| &&
|down 3\n| &&
|forward 7\n| &&
|forward 9\n| &&
|down 8\n| &&
|down 8\n| &&
|up 1\n| &&
|up 8\n| &&
|down 5\n| &&
|up 3\n| &&
|forward 6\n| &&
|forward 4\n| &&
|forward 8\n| &&
|up 4\n| &&
|down 6\n| &&
|forward 2\n| &&
|forward 8\n| &&
|down 1\n| &&
|up 5\n| &&
|down 4\n| &&
|forward 5\n| &&
|up 1\n| &&
|forward 2\n| &&
|down 9\n| &&
|down 2\n| &&
|forward 8\n| &&
|up 3\n| &&
|up 7\n| &&
|forward 3\n| &&
|forward 4\n| &&
|down 7\n| &&
|up 3\n| &&
|down 7\n| &&
|forward 7\n| &&
|up 1\n| &&
|down 3\n| &&
|down 5\n| &&
|down 7\n| &&
|forward 5\n| &&
|down 1\n| &&
|up 9\n| &&
|forward 1\n| &&
|down 6\n| &&
|up 4\n| &&
|down 1\n| &&
|forward 7\n| &&
|forward 2\n| &&
|down 2\n| &&
|forward 2\n| &&
|down 7\n| &&
|down 4\n| &&
|down 7\n| &&
|down 9\n| &&
|down 6\n| &&
|down 2\n| &&
|up 6\n| &&
|forward 8\n| &&
|down 2\n| &&
|down 1\n| &&
|down 8\n| &&
|down 8\n| &&
|down 1\n| &&
|down 7\n| &&
|forward 4\n| &&
|forward 1\n| &&
|down 2\n| &&
|down 1\n| &&
|up 2\n| &&
|down 5\n| &&
|forward 3\n| &&
|forward 7\n| &&
|forward 9\n| &&
|up 5\n| &&
|down 7\n| &&
|down 3\n| &&
|forward 3\n| &&
|down 4\n| &&
|forward 6\n| &&
|forward 1\n| &&
|down 6\n| &&
|up 5\n| &&
|up 6\n| &&
|down 9\n| &&
|forward 9\n| &&
|forward 5\n| &&
|down 3\n| &&
|forward 5\n| &&
|up 4\n| &&
|down 4\n| &&
|down 6\n| &&
|forward 2\n| &&
|forward 2\n| &&
|down 5\n| &&
|down 1\n| &&
|forward 3\n| &&
|forward 5\n| &&
|up 5\n| &&
|down 1\n| &&
|down 5\n| &&
|down 3\n| &&
|down 4\n| &&
|down 2\n| &&
|down 2\n| &&
|forward 5\n| &&
|down 1\n| &&
|down 4\n| &&
|down 6\n| &&
|forward 4\n| &&
|down 1\n| &&
|down 1\n| &&
|down 7\n| &&
|forward 1\n| &&
|down 5\n| &&
|forward 6\n| &&
|forward 7\n| &&
|forward 3\n| &&
|down 6\n| &&
|forward 8\n| &&
|down 8\n| &&
|down 3\n| &&
|up 9\n| &&
|forward 3\n| &&
|up 5\n| &&
|forward 9\n| &&
|forward 3\n| &&
|forward 5\n| &&
|down 3\n| &&
|down 7\n| &&
|down 5\n| &&
|up 5\n| &&
|down 1\n| &&
|up 5\n| &&
|down 5\n| &&
|down 9\n| &&
|down 4\n| &&
|down 2\n| &&
|down 2\n| &&
|up 2\n| &&
|up 1\n| &&
|forward 2\n| &&
|forward 4\n| &&
|up 5\n| &&
|down 1\n| &&
|forward 6\n| &&
|up 7\n| &&
|up 5\n| &&
|down 5\n| &&
|forward 4\n| &&
|down 1\n| &&
|up 4\n| &&
|down 2\n| &&
|forward 3\n| &&
|forward 4\n| &&
|down 4\n| &&
|down 8\n| &&
|down 4\n| &&
|up 3\n| &&
|forward 6\n| &&
|forward 3\n| &&
|forward 1\n| &&
|up 3\n| &&
|forward 6\n| &&
|down 1\n| &&
|up 5\n| &&
|down 5\n| &&
|down 9\n| &&
|down 9\n| &&
|down 4\n| &&
|forward 9\n| &&
|down 6\n| &&
|down 6\n| &&
|forward 2\n| &&
|up 7\n| &&
|down 4\n| &&
|down 4\n| &&
|down 3\n| &&
|up 1\n| &&
|down 4\n| &&
|up 2\n| &&
|forward 9\n| &&
|down 2\n| &&
|down 6\n| &&
|down 6\n| &&
|up 5\n| &&
|down 7\n| &&
|down 6\n| &&
|down 9\n| &&
|down 8\n| &&
|forward 5\n| &&
|down 6\n| &&
|up 3\n| &&
|down 8\n| &&
|up 3\n| &&
|forward 5\n| &&
|down 1\n| &&
|forward 4\n| &&
|forward 3\n| &&
|down 9\n| &&
|down 4\n| &&
|forward 8\n| &&
|forward 8\n| &&
|up 4\n| &&
|forward 7\n| &&
|up 5\n| &&
|down 9\n| &&
|down 2\n| &&
|forward 6\n| &&
|down 4\n| &&
|forward 9\n| &&
|up 1\n| &&
|down 7\n| &&
|down 3\n| &&
|forward 6\n| &&
|up 7\n| &&
|forward 2\n| &&
|forward 1\n| &&
|down 9\n| &&
|up 4\n| &&
|forward 2\n| &&
|forward 6\n| &&
|forward 9\n| &&
|forward 9\n| &&
|down 7\n| &&
|forward 4\n| &&
|down 2\n| &&
|forward 1\n| &&
|forward 8\n| &&
|down 7\n| &&
|down 1\n| &&
|forward 5\n| &&
|forward 5\n| &&
|down 8\n| &&
|up 8\n| &&
|up 1\n| &&
|forward 2\n| &&
|down 8\n| &&
|forward 6\n| &&
|forward 1\n| &&
|forward 2\n| &&
|forward 7\n| &&
|down 3\n| &&
|forward 5\n| &&
|up 6\n| &&
|up 8\n| &&
|down 7\n| &&
|forward 2\n| &&
|forward 5\n| &&
|down 5\n| &&
|forward 8\n| &&
|down 6\n| &&
|down 3\n| &&
|up 2\n| &&
|down 7\n| &&
|forward 5\n| &&
|down 4\n| &&
|forward 3\n| &&
|up 7\n| &&
|up 6\n| &&
|forward 4\n| &&
|forward 7\n| &&
|forward 6\n| &&
|down 4\n| &&
|forward 5\n| &&
|up 3\n| &&
|up 5\n| &&
|down 8\n| &&
|forward 7\n| &&
|forward 2\n| &&
|forward 3\n| &&
|up 4\n| &&
|down 1\n| &&
|up 2\n| &&
|up 1\n| &&
|forward 6\n| &&
|up 3\n| &&
|down 3\n| &&
|forward 7\n| &&
|down 6\n| &&
|forward 9\n| &&
|forward 9\n| &&
|down 7\n| &&
|forward 1\n| &&
|down 9\n| &&
|down 9\n| &&
|forward 8\n| &&
|up 9\n| &&
|up 7\n| &&
|up 4\n| &&
|forward 4\n| &&
|down 3\n| &&
|down 4\n| &&
|forward 4\n| &&
|forward 5\n| &&
|down 2\n| &&
|down 7\n| &&
|down 1\n| &&
|forward 7\n| &&
|down 6\n| &&
|down 6\n| &&
|forward 3\n| &&
|up 1\n| &&
|forward 4\n| &&
|down 5\n| &&
|up 7\n| &&
|up 3\n| &&
|up 9\n| &&
|forward 8\n| &&
|up 4\n| &&
|forward 2\n| &&
|down 2\n| &&
|down 2\n| &&
|up 8\n| &&
|forward 1\n| &&
|forward 3\n| &&
|forward 7\n| &&
|down 7\n| &&
|up 5\n| &&
|down 3\n| &&
|down 4\n| &&
|down 6\n| &&
|forward 5\n| &&
|down 1\n| &&
|forward 5\n| &&
|down 4\n| &&
|forward 8\n| &&
|down 4\n| &&
|forward 6\n| &&
|forward 9\n| &&
|down 5\n| &&
|up 2\n| &&
|down 2\n| &&
|forward 1\n| &&
|forward 5\n| &&
|down 1\n| &&
|down 4\n| &&
|down 4\n| &&
|up 6\n| &&
|forward 7\n| &&
|forward 2\n| &&
|forward 9\n| &&
|down 1\n| &&
|forward 2\n| &&
|forward 6\n| &&
|forward 1\n| &&
|up 9\n| &&
|down 7\n| &&
|down 8\n| &&
|forward 3\n| &&
|forward 5\n| &&
|down 4\n| &&
|forward 2\n| &&
|forward 2\n| &&
|up 8\n| &&
|forward 3\n| &&
|forward 8\n| &&
|forward 5\n| &&
|up 6\n| &&
|forward 6\n| &&
|forward 3\n| &&
|down 4\n| &&
|up 8\n| &&
|down 3\n| &&
|forward 4\n| &&
|forward 3\n| &&
|up 4\n| &&
|forward 7\n| &&
|down 9\n| &&
|forward 3\n| &&
|down 6\n| &&
|forward 9\n| &&
|down 8\n| &&
|forward 6\n| &&
|down 7\n| &&
|down 1\n| &&
|forward 9\n| &&
|down 4\n| &&
|forward 8\n| &&
|forward 5\n| &&
|forward 7\n| &&
|up 5\n| &&
|up 3\n| &&
|down 8\n| &&
|down 5\n| &&
|down 2\n| &&
|up 3\n| &&
|up 7\n| &&
|down 8\n| &&
|forward 6\n| &&
|forward 4\n| &&
|forward 9\n| &&
|forward 6\n| &&
|forward 4\n| &&
|forward 1\n| &&
|down 1\n| &&
|down 3\n| &&
|up 3\n| &&
|up 7\n| &&
|down 9\n| &&
|down 5\n| &&
|forward 1\n| &&
|forward 6\n| &&
|forward 5\n| &&
|down 9\n| &&
|forward 9\n| &&
|forward 5\n| &&
|up 5\n| &&
|forward 8\n| &&
|forward 6\n| &&
|forward 4\n| &&
|down 4\n| &&
|down 6\n| &&
|down 1\n| &&
|forward 1\n| &&
|down 6\n| &&
|forward 8\n| &&
|down 3\n| &&
|down 6\n| &&
|down 5\n| &&
|forward 3\n| &&
|down 3\n| &&
|down 8\n| &&
|up 6\n| &&
|forward 6\n| &&
|down 6\n| &&
|down 4\n| &&
|down 8\n| &&
|down 9\n| &&
|down 3\n| &&
|down 4\n| &&
|down 5\n| &&
|forward 4\n| &&
|down 7\n| &&
|down 8\n| &&
|up 4\n| &&
|forward 4\n| &&
|down 9\n| &&
|forward 1\n| &&
|forward 1\n| &&
|down 6\n| &&
|up 3\n| &&
|up 6\n| &&
|down 8\n| &&
|up 7\n| &&
|forward 3\n| &&
|down 6\n| &&
|down 1\n| &&
|down 4\n| &&
|up 4\n| &&
|down 9\n| &&
|forward 1\n| &&
|down 3\n| &&
|up 1\n| &&
|forward 8\n| &&
|up 4\n| &&
|up 6\n| &&
|up 4\n| &&
|down 4\n| &&
|up 5\n| &&
|up 3\n| &&
|down 1\n| &&
|down 6\n| &&
|forward 9\n| &&
|down 2\n| &&
|forward 9\n| &&
|forward 8\n| &&
|down 2\n| &&
|forward 8\n| &&
|up 5\n| &&
|forward 5\n| &&
|forward 5\n| &&
|forward 4\n| &&
|up 8\n| &&
|down 3\n| &&
|forward 3\n| &&
|down 4\n| &&
|up 1\n| &&
|forward 4\n| &&
|up 7\n| &&
|down 1\n| &&
|down 4\n| &&
|forward 1\n| &&
|forward 9\n| &&
|down 7\n| &&
|forward 4\n| &&
|down 5\n| &&
|down 7\n| &&
|forward 9\n| &&
|down 2\n| &&
|down 2\n| &&
|down 1\n| &&
|down 2\n| &&
|forward 8\n| &&
|down 6\n| &&
|forward 5\n| &&
|down 2\n| &&
|down 1\n| &&
|up 4\n| &&
|forward 7\n| &&
|down 1\n| &&
|down 5\n| &&
|down 7\n| &&
|down 6\n| &&
|down 6\n| &&
|up 8\n| &&
|forward 3\n| &&
|up 8\n| &&
|up 9\n| &&
|down 2\n| &&
|down 1\n| &&
|down 5\n| &&
|up 8\n| &&
|forward 4\n| &&
|forward 6\n| &&
|down 2\n| &&
|down 3\n| &&
|forward 2\n| &&
|forward 2\n| &&
|forward 2\n| &&
|forward 3\n| &&
|down 7\n| &&
|forward 3\n| &&
|down 4\n| &&
|up 1\n| &&
|down 2\n| &&
|down 9\n| &&
|up 4\n| &&
|down 8\n| &&
|up 7\n| &&
|down 6\n| &&
|down 7\n| &&
|down 6\n| &&
|forward 6\n| &&
|down 4\n| &&
|forward 2\n| &&
|down 7\n| &&
|down 1\n| &&
|forward 2\n| &&
|forward 5\n| &&
|forward 6\n| &&
|down 1\n| &&
|down 4\n| &&
|forward 2\n| &&
|down 4\n| &&
|down 6\n| &&
|down 8\n| &&
|forward 9\n| &&
|down 8\n| &&
|forward 5\n| &&
|down 7\n| &&
|forward 5\n| &&
|up 1\n| &&
|down 1\n| &&
|down 9\n| &&
|down 3\n| &&
|forward 3\n| &&
|forward 5\n| &&
|down 6\n| &&
|forward 6\n| &&
|up 3\n| &&
|down 4\n| &&
|down 4\n| &&
|forward 7\n| &&
|forward 3\n| &&
|down 5\n| &&
|down 3\n| &&
|forward 7\n| &&
|up 5\n| &&
|forward 1\n| &&
|down 6\n| &&
|forward 1\n| &&
|forward 9\n| &&
|forward 9\n| &&
|up 9\n| &&
|forward 5\n| &&
|up 5\n| &&
|forward 6\n| &&
|down 8\n| &&
|up 4\n| &&
|up 8\n| &&
|forward 9\n| &&
|forward 4\n| &&
|down 5\n| &&
|down 2\n| &&
|down 9\n| &&
|forward 3\n| &&
|forward 6\n| &&
|forward 2\n| &&
|up 4\n| &&
|down 4\n| &&
|forward 3\n| &&
|down 8\n| &&
|down 3\n| &&
|up 3\n| &&
|forward 8\n| &&
|down 4\n| &&
|forward 4\n| &&
|forward 4\n| &&
|up 9\n| &&
|down 1\n| &&
|up 5\n| &&
|up 5\n| &&
|forward 8\n| &&
|forward 4\n| &&
|forward 5\n| &&
|forward 1\n| &&
|forward 3\n| &&
|forward 8\n| &&
|down 1\n| &&
|forward 2\n| &&
|forward 7\n| &&
|down 4\n| &&
|down 3\n| &&
|down 4\n| &&
|up 7\n| &&
|forward 9\n| &&
|forward 7\n| &&
|down 8\n| &&
|forward 2\n| &&
|down 4\n| &&
|up 9\n| &&
|down 9\n| &&
|down 9\n| &&
|up 2\n| &&
|down 9\n| &&
|down 9\n| &&
|down 6\n| &&
|up 9\n| &&
|up 6\n| &&
|down 7\n| &&
|forward 3\n| &&
|forward 9\n| &&
|forward 2\n| &&
|down 4\n| &&
|up 4\n| &&
|forward 1\n| &&
|up 1\n| &&
|down 6\n| &&
|down 3\n| &&
|down 2\n| &&
|up 6\n| &&
|down 5\n| &&
|down 8\n| &&
|up 4\n| &&
|forward 1\n| &&
|down 1\n| &&
|down 4\n| &&
|down 8\n| &&
|down 5\n| &&
|forward 2\n| &&
|down 5\n| &&
|forward 3\n| &&
|forward 1\n| &&
|forward 9\n| &&
|forward 4\n| &&
|down 6\n| &&
|down 4\n| &&
|down 3\n| &&
|forward 5\n| &&
|forward 4\n| &&
|down 1\n| &&
|up 7\n| &&
|down 4\n| &&
|up 3\n| &&
|forward 2\n| &&
|forward 4\n| &&
|up 2\n| &&
|up 9\n| &&
|forward 4\n| &&
|down 5\n| &&
|forward 9\n| &&
|up 1\n| &&
|forward 8\n| &&
|down 9\n| &&
|down 6\n| &&
|down 6\n| &&
|down 2\n| &&
|down 2\n| &&
|down 3\n| &&
|forward 8\n| &&
|down 2\n| &&
|down 5\n| &&
|forward 4\n| &&
|up 3\n| &&
|down 4\n| &&
|up 6\n| &&
|forward 7\n| &&
|up 2\n| &&
|down 6\n| &&
|down 8\n| &&
|forward 1\n| &&
|down 8\n| &&
|down 9\n| &&
|down 2\n| &&
|forward 3\n| &&
|forward 9\n| &&
|up 7\n| &&
|down 1\n| &&
|down 5\n| &&
|up 7\n| &&
|down 5\n| &&
|up 8\n| &&
|up 4\n| &&
|down 6\n| &&
|forward 1\n| &&
|forward 6\n| &&
|forward 9\n| &&
|forward 6\n| &&
|forward 6\n| &&
|forward 9\n| &&
|forward 8\n| &&
|down 8\n| &&
|down 8\n| &&
|down 4\n| &&
|down 7\n| &&
|down 9\n| &&
|up 9\n| &&
|down 7\n| &&
|down 2\n| &&
|forward 2\n| &&
|down 5\n| &&
|down 3\n| &&
|down 1\n| &&
|down 4\n| &&
|down 2\n| &&
|down 1\n| &&
|up 2\n| &&
|forward 6\n| &&
|down 3\n| &&
|down 3\n| &&
|down 1\n| &&
|forward 8\n| &&
|down 3\n| &&
|forward 1\n| &&
|forward 3\n| &&
|down 1\n| &&
|up 7\n| &&
|down 9\n| &&
|forward 5\n| &&
|forward 8\n| &&
|up 7\n| &&
|down 4\n| &&
|down 3\n| &&
|down 1\n| &&
|forward 2\n| &&
|forward 9\n| &&
|up 5\n| &&
|down 2\n| &&
|forward 6\n| &&
|forward 6\n| &&
|forward 2\n| &&
|forward 1\n| &&
|forward 1\n| &&
|down 9\n| &&
|forward 6\n| &&
|forward 6\n| &&
|down 2\n| &&
|down 6\n| &&
|up 5\n| &&
|forward 5\n| &&
|up 4\n| &&
|forward 4\n| &&
|down 2\n| &&
|down 2\n| &&
|down 7\n| &&
|down 1\n| &&
|down 4\n| &&
|forward 3\n| &&
|forward 3\n| &&
|up 8\n| &&
|down 8\n| &&
|forward 5\n| &&
|up 4\n| &&
|up 9\n| &&
|up 6\n| &&
|up 6\n| &&
|down 7\n| &&
|forward 2\n| &&
|up 1\n| &&
|forward 2\n| &&
|forward 4\n| &&
|forward 4\n| &&
|forward 2\n| &&
|forward 4\n| &&
|down 6\n| &&
|down 3\n| &&
|forward 9\n| &&
|forward 3\n| &&
|down 2\n| &&
|forward 6\n| &&
|forward 6\n| &&
|forward 4\n| &&
|forward 8\n| &&
|up 1\n| &&
|down 1\n| &&
|forward 1\n| &&
|down 7\n| &&
|up 6\n| &&
|up 8\n| &&
|down 1\n| &&
|down 4\n| &&
|down 3\n| &&
|up 4\n| &&
|forward 4\n| &&
|forward 5\n| &&
|down 5\n| &&
|down 8\n| &&
|up 7\n| &&
|down 2\n| &&
|down 6\n| &&
|forward 5|.
  ENDMETHOD.

ENDCLASS.
